### ISSUE TITLE
Appearing upside down after a date

### ISSUE THREAD

**Issue by RodoxVR** [IllusionMods/KKS_VR#21] opened 2022-06-29 23:38 UTC
When u say tourism Together with a girl and when the random spot is the waterfall u are flipped upside down when diaglogue ends.

Atleast the camera is... the character is still standing on the ground.

**Comment by momspaghetti123** [comment] 2023-05-26 01:53
Can confirm. The mod works great and I highly appreciate the creator of this fork... But this bug screws up the game not even a full day in. Eventually I got stick and started walking outside the map, till the game crashed.

Really hope this will get fixed sometime. This is quite a fun way to play - but this makes it unplayable.

**Comment by RodoxVR** [comment] 2023-05-29 18:13
Yeah, and i found out that its not only on the waterfall, it seems its random at times, plus on occassion it does it also after loading the map is finished when first entering the world.

**Comment by ManlyMarco** [comment] 2023-05-29 20:46
Does this only reliably happen when being asked by the girl to go to the waterfall scene or can you suggest it too?

**Comment by momspaghetti123** [comment] 2023-05-29 21:35
Suggesting works too, sometimes it just happens even if you initiate a chat with any girl. I don't know if any other scenes have this bug as well, but so far I've only start experiencing the bug while in the waterfall scene.
[output_log.txt](https://github.com/IllusionMods/KKS_VR/files/11594234/output_log.txt)
Here's the output_log.txt of the game where I started experiencing the upside down crash until I got stuck into an object, managed to get outside the playable area and eventually crashed.

**Comment by ManlyMarco** [comment] 2023-05-30 21:59
@RodoxVR @momspaghetti123 What VR headsets are you using?

**Comment by momspaghetti123** [comment] 2023-05-30 22:40
> @RodoxVR @momspaghetti123 What VR headsets are you using?

Oculus Rift S.

**Comment by RodoxVR** [comment] 2023-05-31 05:50
@ManlyMarco I'm using Vive Pro 2 with Steam Index controllers.

**Comment by RodoxVR** [comment] 2023-05-31 05:54
> @RodoxVR @momspaghetti123 What VR headsets are you using?

 I'm using Vive Pro 2 with Steam Index controllers.

Also on SteamVR.

**Comment by RodoxVR** [comment] 2023-05-31 06:01
As promised... i donated some money for your time on your patreon page.

You are a legend for making this mod, u have my gratitude.

**Comment by ManlyMarco** [comment] 2023-05-31 09:24
Can you test if this build works any better? [KKS_MainGameVR.zip](https://github.com/IllusionMods/KKS_VR/files/11611066/KKS_MainGameVR.zip)
Send the output_log if it doesn't (immediately after the bug happens).

**Comment by momspaghetti123** [comment] 2023-05-31 09:51
On it 🫡

**Comment by ManlyMarco** [comment] 2023-05-31 20:37
Latest build [KKS_MainGameVR.zip](https://github.com/IllusionMods/KKS_VR/files/11618675/KKS_MainGameVR.zip)

**Comment by RodoxVR** [comment] 2023-05-31 23:08
Here's my log:

[output_log.txt](https://github.com/IllusionMods/KKS_VR/files/11619429/output_log.txt)

Description: asked a girl outside the school building to tourism together and the place was waterfall, it did the upside down thing again, after this i quit the game.

Used the latest build 2 hours ago from this post above, play session was about 1 hour and 30 min before it happened, i kept asking to do things together till it happened.
---------------------------------------------------------------------
Not sure if u are aware but when talking to a girl now the camera is zoomed out very far outside the map but when i talk to girl camera resets to the correct position, this happens only after using the new build.

Hope this is helpful.

**Comment by ManlyMarco** [comment] 2023-06-01 07:52
Oops, I forgot to mention you need to change the `Log level` setting of `KKS_MainGameVR` in plugin settings from `Info` to `Debug` (restart the game afterwards). Sorry about that, without that the log doesn't show the info I need.

The outside of map issue should be fixed in the latest build I posted above.

**Comment by RodoxVR** [comment] 2023-06-01 17:28
Alright,

Then we'll just have to try again, not a big problem.
I do not have time tomorrow but in the weekend ill have another go.

**Comment by ManlyMarco** [comment] 2023-06-02 21:19
Latest build, more changes to positioning code, and title skybox [KKS_MainGameVR.zip](https://github.com/IllusionMods/KKS_VR/files/11638939/KKS_MainGameVR.zip)

**Comment by momspaghetti123** [comment] 2023-06-03 00:54
Tested out the latest build, and experienced the bug not even much in, less than 30 minutes of playing. Happened right after a date ended, and then I quit the game.
[output_log.txt](https://github.com/IllusionMods/KKS_VR/files/11640073/output_log.txt)

Some feedback regarding other changes of this build:
VR title skybox looks nice, I approve.

There are some peculiarities regarding the updated positioning code:
The camera bug that Rodox had mentioned still happens, your camera moves way outside the map when you initiate chat with a girl. It then "fixes" itself, after you do any kind of talk, but your camera gets moved behind the girl, so it's better, but not quite there. However, before this incorrect position, the correct camera pos with the girl facing you appears for a split second. The far-outside the map camera bug only happens when you talk to a girl the first time in a particular map, subsequent encounters in the same map position your camera in the last (almost correct) position that you were in with the previous girl. The aforementioned camera bug reappears after changing map.
Interestingly enough, the camera behaves differently after initiating a date. The camera position is almost right, but super close to the girl in dates. The camera position remains this way until you try to turn with the School tool, at which your camera gets transported to a random place in the room (height still correct and didn't experience out-of-bounds though). Camera moves back to the almost-correct-but-way-too-close pos after progressing the convo, til/if you try to turn again.

Hope all this will be useful, thanks for the work and cooperation.

**Comment by ManlyMarco** [comment] 2023-06-03 16:58
Alright, I THINK it's actually fixed now 
[KKS_MainGameVR.zip](https://github.com/IllusionMods/KKS_VR/files/11643264/KKS_MainGameVR.zip)
Fingers crossed.

**Comment by RodoxVR** [comment] 2023-06-03 23:19
Ive send both main directory output log and the bepinex log, as im not sure wich one to send u. Might be both helpful ?

Here's my output log:

[output_log.txt](https://github.com/IllusionMods/KKS_VR/files/11644436/output_log.txt)

Here's Bepinex Log:
[LogOutput.log](https://github.com/IllusionMods/KKS_VR/files/11644437/LogOutput.log)

Description:

Played about 1 hour 30 min again, invited girl to tourism together, after the second time that waterfall date appeared the camera went upside down, so it doesnt always do it.
But its almost always the waterfall that it happens.
------------------------------------------------------------------

Camera bug when u go talk to a girl spawns in wrong but not outside map anymore, sometimes its correct but most of the time it spawns on her side (near her) or on her back or looking away from her.

**Comment by ManlyMarco** [comment] 2023-06-04 06:45
I see no reason for it to still happen, and I still can't reproduce the issue. The waterfall events work fine for me. Send your game save with exact steps on how to reproduce the issue, ideally within a couple of minutes not hours.

**Comment by RodoxVR** [comment] 2023-06-04 08:40
save:
https://mega.nz/folder/PPQ1xL7a#QzBBwdJPU1CtIOVAhUbUzg

Well it happened also on my old pc, it has always done it with multiple saves.

Have the latest better repack from [ScrewThisNoise] Koikatsu Sunshine EX BetterRepack R9 
As i'm always using those.
Then:

1.  increase relationship status to increase chance she says yes for tourism together.
2. ask girls to go tourism together untill waterfall scene.
3. if it doesnt go upside down try again as it doesnt always trigger the bug.

it sometimes takes multiple times to trigger it so be patient.

**Comment by momspaghetti123** [comment] 2023-06-04 20:19
I will test out as well to see if I concur.

**Comment by momspaghetti123** [comment] 2023-06-04 21:25
Yum, I see Crossfader was implemented to the plugin. I could test it out together with the tests for the bug right now. Does it conflict with KKS_Crossfader (do I need to uninstall that?)?

**Comment by momspaghetti123** [comment] 2023-06-05 15:33
Can concur. It didn't even take long, even though I wasn't rushing to get the bug. Couldn't find the BepInEx log that was supposedly going to be generated - but found that the output_log.txt did get all the VR debug details so uploading that.
This time it happened after ending a date in the waterfall, like usual. To note, last time I experienced the bug, it was in a room where the date took place in.
What might help with catching this bug: either the camera also gets the yaw inverted, or the controls also glitch, because when I enter a map in the upside-down state, pressing forward on the joystick again brings me back to the previous room, instead of me traversing away from the exit/entry point, like it would usually be.

[output_log.txt](https://github.com/IllusionMods/KKS_VR/files/11654166/output_log.txt)
Also:
Camera positioning is almost entirely fixed: Though the camera position should update after initiating a chat with a girl, not only after doing any first action during the chat. Dating has the too-close camera, which gets fixed after you try to turn with the School tool, moving back to the too-close camera after the next line is said.

**Comment by ManlyMarco** [comment] 2023-06-05 17:14
The thing is I completely strip rotation other than facing left/right so it shouldn't be possible to get flipped.
What's does the too close camera look like?

**Comment by ManlyMarco** [comment] 2023-06-20 21:06
There's a good chance this got fixed in v1.2. If anyone is able to verify, please let me know.

**Comment by RodoxVR** [comment] 2023-06-22 15:21
First of all Marco, what a great update!
So many fixes.

Especially the AnimationCrossFader is a welcome edition for some extra boob jiggle :3 and the fact that i can now open the menu without touching the mouse, u truly are a wizard.

-------------------------------------------------------------------------------------------------------------------------------------------
Now about this appearing upside down bug, i have not noticed it during my test session yesterday... but i only got the waterfall scene twice so it needs more extensive testing.

The camera still doesnt face the girl when u start talking, a minor issue that i can live with for now as it corrects itself when u continue the conversation.

All in all great job, looking forward to my next play test when i have more time.

**Comment by momspaghetti123** [comment] 2023-07-12 00:04
Sorry for the late reply, been busy. I've tested out the update and played through two in-game days. Happy to confirm that it's very likely fixed, as I have not ever been able to get past the first day without catching the bug.
Highly appreciate the binding fixed as well, as I can now warp and save.

Camera is still very wonky and inconsistent between dating and talking. But thankfully, as Rodox has mentioned, it gets corrected after initiating the first line.

I'd recommend a  H scene controls rework (or at least more customizability for the bindings like multi-buttons and mode switches) and setting fade to black, but I can open issues for that, and potentially even do a PR or two. 

This issue can be closed.

**Comment by ManlyMarco** [comment] 2023-07-12 18:49
Nice, that's one annoying bug down. The camera thing is the second most annoying bug to fix because of how janky the whole setup is. I bet it could be fixed for good by a rewrite but that's a ton of work that I don't feel like doing for the little return.

Definitely make new issues for the suggestions, and I'd absolutely love some PRs :)

**Closed** 2023-07-12 18:49 UTC
Labels: bug
